import "./globals.css";
import { Inter, Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["400", "600"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} h-screen w-full`}>
        {children}
        <button className="fixed top-0 right-0 mt-12 mr-10 bg-[#5AA0FD] py-2 px-4 rounded-full text-white">
          Connect Wallet
        </button>
      </body>
    </html>
  );
}
