import TNavbar from "../components/TNavbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function StudentLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white h-screen w-full flex justify-centerz">
        <div className="w-[340px] h-screen">
          <TNavbar />
        </div>

        <main className="">{children}</main>
      </body>
    </html>
  );
}
